---

- hosts: all, localhost
  become: true
  pre_tasks:
 
  - name: install updates (CentOS)
    tags: always 
    package:
      update_cache: yes
    changed_when: false    
    #when: ansible_distribution == "CentOS Stream" 
 
  -  name: install httpd package and php
     tags: httpd, php, samba, cifs-utils
     package:
       name:
         - httpd
         - php
         - samba
         - cifs-utils
       state: latest
       update_cache: yes
      #when: ansible_distribution == "Centos"
  
  - name: change e-mail adress for admin
    lineinfile: 
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    register: httpd

  - name: copy deafult html file for site
    tags: apache,apache2,httpd 
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644 

  - name: restart httpd service
    service:
      name: httpd
      state: restarted
      enabled: yes
    when: httpd.changed

- hosts: all, localhost
  become: true
  tasks:
 
 
