---
- hosts: all
  become: yes
  tasks:
  - name: Change password for user ansible_user
    user:
      name: ansible_user
      password: "$6$rounds=656000$gIu2hA2FJv/V7X.G$KDV7f5Pm/uP5o5BtDp1UNrJYk0h7VcWd08uJ7GX9xnQb7l5W5BO5b5C5r547aD8p5BhE5KM82ltZ5F5k5.5H5/"
      update_password: always

